# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatSwift

  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  target 'ChatSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatSwiftUITests' do
    # Pods for testing
  end

end
